var PENDING_STATE = "PENDING";
var APPROVED_STATE = "APPROVED";
var DENIED_STATE = "DENIED";
var LOG_SHEET = 'Logs';
var DEPLOY_ID = "INSERT_HERE_DEPLOYURL";
var APPROVER_EMAIL = "INSERT_APPROVER_EMAIL";
